"""2x2x2 state module, rebuilt on cubing.js's own KPuzzle definition.

Prior implementation used a hand-rolled 8-corner basis whose "face turns"
were NOT standard cubing 2x2x2 turns: the canonical quotient collapsed frames,
so optimal solutions (e.g. ``L'`` for the scramble ``R``) did NOT undo the
cube that cubing.js displays.  This module instead derives every move action
directly from the cubing.js ``2x2x2`` KPuzzle definition (U, x, y primitives
with permutation + orientationDelta; L/F/R/B/D via the ``[g: h]`` conjugations
= ``g h g^-1``), so the state algebra matches the <twisty-player> exactly.

State conventions (widely used, matches ``KPattern.patternData``):

* PHYSICAL (8-corner) state: ``(pieces, orient)`` pairs of len-8 tuples.
  Applying a move with action ``(perm, delta)``:
  ``new_pieces[i] = pieces[perm[i]];  new_orient[i] = (orient[perm[i]] + delta[i]) % 3``.
* CANONICAL (7-corner) state: the classic rotation quotient used by the BFS
  table.  The unique whole-cube rotation (from the 24 rotations generated by
  the definition's ``x``/``y`` moves) that puts piece 7 in slot 7 with
  orientation 0 fixes the frame; slots 0..6 read off as ``(perm7, orient7)``.

The BFS distance table (``bfs_solver``) is indexed by these canonical 7-states
— distances are rotation-quotient distances, perfect as an admissible
heuristic for the physical solver that emits the displayed moves.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# The cubing.js 2x2x2 KPuzzle definition (definition of record).
# ---------------------------------------------------------------------------

_DEF = {
    "moves": {
        "U": {
            "permutation": (1, 2, 3, 0, 4, 5, 6, 7),
            "orientationDelta": (0, 0, 0, 0, 0, 0, 0, 0),
        },
        "x": {
            "permutation": (4, 0, 3, 5, 7, 6, 2, 1),
            "orientationDelta": (2, 1, 2, 1, 1, 2, 1, 2),
        },
        "y": {
            "permutation": (1, 2, 3, 0, 7, 4, 5, 6),
            "orientationDelta": (0, 0, 0, 0, 0, 0, 0, 0),
        },
    },
    "derivedMoves": {
        # [g: h] == conjugation g h g^-1
        "z": "[x: y]",
        "L": "[z: U]",
        "F": "[x: U]",
        "R": "[z': U]",
        "B": "[x': U]",
        "D": "[x2: U]",
    },
}

MOVES = (
    "U", "U'", "U2",
    "D", "D'", "D2",
    "L", "L'", "L2",
    "R", "R'", "R2",
    "F", "F'", "F2",
    "B", "B'", "B2",
)


# ---------------------------------------------------------------------------
# Move composition algebra on (perm, delta) actions.
# ---------------------------------------------------------------------------


def _compose(A, B):
    """Action of applying ``B`` then ``A`` (as group elements on a pattern)."""
    (pa, da) = A
    (pb, db) = B
    perm = tuple(pa[pb[i]] for i in range(8))
    delta = tuple((da[pb[i]] + db[i]) % 3 for i in range(8))
    return perm, delta


def _inverse(A):
    """Group inverse action."""
    (p, d) = A
    pinv = [0] * 8
    for i in range(8):
        pinv[p[i]] = i
    pinv = tuple(pinv)
    delta = tuple((-d[pinv[i]]) % 3 for i in range(8))
    return pinv, delta


def _conjugate(g, h):
    """``[g: h]`` -- h conjugated by g: g h g^-1."""
    return _compose(g, _compose(h, _inverse(g)))


def _build_actions():
    U = tuple(_DEF["moves"]["U"]["permutation"]), tuple(_DEF["moves"]["U"]["orientationDelta"])
    x = tuple(_DEF["moves"]["x"]["permutation"]), tuple(_DEF["moves"]["x"]["orientationDelta"])
    y = tuple(_DEF["moves"]["y"]["permutation"]), tuple(_DEF["moves"]["y"]["orientationDelta"])

    x2 = _compose(x, x)
    xp = _inverse(x)
    x2p = _inverse(x2)
    y2 = _compose(y, y)
    yp = _inverse(y)
    y2p = _inverse(y2)
    z = _conjugate(x, y)          # "[x: y]"
    zp = _inverse(z)
    z2 = _compose(z, z)
    z2p = _inverse(z2)

    base = {
        "U": U, "U'": _inverse(U), "U2": _compose(U, U),
        "x": x, "x'": xp, "x2": x2,
        "y": y, "y'": yp, "y2": y2,
        "z": z, "z'": zp, "z2": z2,
        "L": _conjugate(z, U),
        "F": _conjugate(x, U),
        "R": _conjugate(zp, U),
        "B": _conjugate(xp, U),
        "D": _conjugate(x2, U),
    }
    actions = {}
    for face in "UDLRFB":
        m = base[face]
        actions[face] = m
        actions[face + "'"] = _inverse(m)
        actions[face + "2"] = _compose(m, m)
    actions.update({
        "x": x, "x'": xp, "x2": x2,
        "y": y, "y'": yp, "y2": y2,
        "z": z, "z'": zp, "z2": z2,
    })
    return actions


ACTIONS = _build_actions()


def inverse(move):
    """Algebraic inverse of a move name."""
    if move.endswith("2"):
        return move
    return move[0] + ("'" if not move.endswith("'") else "")


# ---------------------------------------------------------------------------
# Physical (8-corner) states -- what cubing.js actually displays.
# ---------------------------------------------------------------------------

PHYS_SOLVED = (tuple(range(8)), (0,) * 8)


def apply_physical(state, move):
    """Apply ``move`` to an 8-corner physical state (cubing.js semantics)."""
    pieces, orient = state
    perm, delta = ACTIONS[move]
    new_pieces = tuple(pieces[perm[i]] for i in range(8))
    new_orient = tuple((orient[perm[i]] + delta[i]) % 3 for i in range(8))
    return new_pieces, new_orient


def apply_physical_alg(state, alg):
    for move in alg:
        state = apply_physical(state, move)
    return state


def is_solved_physical(state):
    return state == PHYS_SOLVED


# ---------------------------------------------------------------------------
# Rotation subgroup: the 24 rotations generated by the def's x / y moves.
# ---------------------------------------------------------------------------

_ROT_GEN = ("x", "x'", "y", "y'")


def _build_rotations():
    """All distinct whole-cube rotations as actions ((word), action)."""
    id_action = (tuple(range(8)), (0,) * 8)
    seen_ids = {id_action}
    by_action = {id_action: ()}
    frontier = [id_action]
    while frontier:
        nxt = []
        for cur in frontier:
            for name in _ROT_GEN:
                child = _compose(ACTIONS[name], cur)
                if child not in seen_ids:
                    seen_ids.add(child)
                    by_action[child] = by_action[cur] + (name,)
                    nxt.append(child)
        frontier = nxt
    assert len(seen_ids) == 24, len(seen_ids)
    return [by_action[a] for a in sorted(seen_ids, key=str)]


ROT_WORDS = tuple(_build_rotations())   # identity word first by lexical sort


def rotate_physical(state, rot_word):
    """Apply a whole-cube rotation (a tuple of x/y/z move names) to a state."""
    return apply_physical_alg(state, rot_word)


# ---------------------------------------------------------------------------
# Canonical 7-corner frame and its move tables (quotient model).
# ---------------------------------------------------------------------------


def canonical7(state8):
    """Rotation quotient representative: piece 7 in slot 7 with twist 0.

    Returns ``(perm7, orient7)``.  Raises if the state is not legal under the
    definition (no rotation puts piece 7 home with twist 0).
    """
    pieces, orient = state8
    for word in ROT_WORDS:
        p8, o8 = apply_physical_alg(state8, word)
        if p8[7] == 7 and o8[7] == 0:
            return p8[:7], o8[:7]
    raise RuntimeError("no canonical frame found for 8-corner state")


def to_full(perm7, orient7):
    return perm7 + (7,), orient7 + (0,)


def from_full(p8, o8):
    if p8[7] != 7 or o8[7] != 0:
        raise ValueError("8-corner state is not canonical")
    return p8[:7], o8[:7]


def _build_move_tables():
    """7-corner canonical-effective move maps (group action axiom).

    A physical face turn followed by re-canonicalisation is a fixed map on the
    seven represented corners; assert state-independence while building.
    """
    tables = {}
    for move in MOVES:
        perm, delta = ACTIONS[move]
        slot_map = [0] * 7
        orient_map = [None] * 7
        for i in range(7):
            new_slots = []
            new_orient = []
            for c in range(3):
                p8 = tuple(range(8))
                o8 = [0] * 8
                o8[i] = c
                p8n, o8n = apply_physical(to_full(p8, tuple(o8)), move)
                c7 = canonical7((p8n, o8n))
                j = c7[0].index(i)
                new_slots.append(j)
                new_orient.append(c7[1][j])
            assert len(set(new_slots)) == 1, (move, i, new_slots)
            slot_map[i] = new_slots[0]
            orient_map[i] = tuple(new_orient)
        tables[move] = (tuple(slot_map), tuple(orient_map))
    return tables


MOVE_TABLES = _build_move_tables()

SOLVED = (tuple(range(7)), (0,) * 7)


def apply_move(state, move):
    """Return the canonical 7-corner state after ``move`` (quotient moves)."""
    perm, orient = state
    slot_map, orient_map = MOVE_TABLES[move]
    new_perm = [0] * 7
    new_orient = [0] * 7
    for i in range(7):
        j = slot_map[i]
        new_perm[j] = perm[i]
        new_orient[j] = orient_map[i][orient[i]]
    return tuple(new_perm), tuple(new_orient)


def is_solved(state):
    return state == SOLVED


def apply_alg(state, alg):
    for move in alg:
        state = apply_move(state, move)
    return state